#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
# autospec version: v21
# autospec commit: e822d6e48dc0
#
# Source0 file verified with key 0xB4322F04D67658D8 (ffmpeg-devel@ffmpeg.org)
#
Name     : compat-ffmpeg-6
Version  : 6.0
Release  : 98
URL      : https://ffmpeg.org/releases/ffmpeg-6.0.tar.xz
Source0  : https://ffmpeg.org/releases/ffmpeg-6.0.tar.xz
Source1  : https://ffmpeg.org/releases/ffmpeg-6.0.tar.xz.asc
Source2  : B4322F04D67658D8.pkey
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0 GPL-3.0 LGPL-2.1 LGPL-3.0
Requires: compat-ffmpeg-6-lib = %{version}-%{release}
Requires: compat-ffmpeg-6-license = %{version}-%{release}
BuildRequires : Vulkan-Headers-dev
BuildRequires : buildreq-configure
BuildRequires : gmp-dev
BuildRequires : gnupg
BuildRequires : ladspa_sdk-dev
BuildRequires : libass-dev
BuildRequires : libtheora-dev
BuildRequires : nasm
BuildRequires : pkgconfig(SvtAv1Enc)
BuildRequires : pkgconfig(aom)
BuildRequires : pkgconfig(dav1d)
BuildRequires : pkgconfig(jack)
BuildRequires : pkgconfig(libdrm)
BuildRequires : pkgconfig(libmfx)
BuildRequires : pkgconfig(libopenjp2)
BuildRequires : pkgconfig(libopenmpt)
BuildRequires : pkgconfig(libpulse)
BuildRequires : pkgconfig(librist)
BuildRequires : pkgconfig(librsvg-2.0)
BuildRequires : pkgconfig(libssh)
BuildRequires : pkgconfig(libv4l2)
BuildRequires : pkgconfig(libva)
BuildRequires : pkgconfig(libwebp)
BuildRequires : pkgconfig(libxml-2.0)
BuildRequires : pkgconfig(openssl)
BuildRequires : pkgconfig(opus)
BuildRequires : pkgconfig(sdl2)
BuildRequires : pkgconfig(speex)
BuildRequires : pkgconfig(srt)
BuildRequires : pkgconfig(vapoursynth-script)
BuildRequires : pkgconfig(vidstab)
BuildRequires : pkgconfig(vorbis)
BuildRequires : pkgconfig(vpx)
BuildRequires : pkgconfig(x264)
BuildRequires : pkgconfig(x265)
BuildRequires : pkgconfig(zimg)
BuildRequires : rtmpdump-dev
BuildRequires : xvidcore-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: 0001-configure-do-not-die-if-unknown-option-is-found.patch

%description
FFmpeg is a collection of libraries and tools to process multimedia content
such as audio, video, subtitles and related metadata.

%package lib
Summary: lib components for the compat-ffmpeg-6 package.
Group: Libraries
Requires: compat-ffmpeg-6-license = %{version}-%{release}

%description lib
lib components for the compat-ffmpeg-6 package.


%package license
Summary: license components for the compat-ffmpeg-6 package.
Group: Default

%description license
license components for the compat-ffmpeg-6 package.


%prep
mkdir .gnupg
chmod 700 .gnupg
gpg --homedir .gnupg --import %{SOURCE2}
gpg --homedir .gnupg --status-fd 1 --verify %{SOURCE1} %{SOURCE0} > gpg.status
grep -E '^\[GNUPG:\] (GOODSIG|EXPKEYSIG) B4322F04D67658D8' gpg.status
%setup -q -n ffmpeg-6.0
cd %{_builddir}/ffmpeg-6.0
%patch -P 1 -p1
pushd ..
cp -a ffmpeg-6.0 buildavx2
popd
pushd ..
cp -a ffmpeg-6.0 buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1731027632
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fno-semantic-interposition -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fno-semantic-interposition -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fno-semantic-interposition -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fno-semantic-interposition -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%configure --disable-static --disable-debug \
--disable-static \
--disable-stripping \
--enable-lto \
--enable-fontconfig \
--enable-gmp \
--enable-gnutls \
--enable-gpl \
--enable-ladspa \
--enable-libaom \
--enable-libass \
--enable-libdav1d \
--enable-libdrm \
--enable-libfreetype \
--enable-libfribidi \
--enable-libjack \
--enable-libmfx \
--enable-libopenjpeg \
--enable-libopenmpt \
--enable-libopus \
--enable-libpulse \
--enable-librist \
--enable-librsvg \
--enable-libspeex \
--enable-libsrt \
--enable-libssh \
--enable-libsvtav1 \
--enable-libtheora \
--enable-libv4l2 \
--enable-libvidstab \
--enable-libvorbis \
--enable-libvpx \
--enable-libwebp \
--enable-libx264 \
--enable-libx265 \
--enable-libxcb \
--enable-libxml2 \
--enable-libxvid \
--enable-libzimg \
--enable-shared \
--enable-vapoursynth \
--enable-version3 \
--enable-vulkan \
--disable-asm
make  %{?_smp_mflags}

unset PKG_CONFIG_PATH
pushd ../buildavx2/
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -march=x86-64-v3 "
%configure --disable-static --disable-debug \
--disable-static \
--disable-stripping \
--enable-lto \
--enable-fontconfig \
--enable-gmp \
--enable-gnutls \
--enable-gpl \
--enable-ladspa \
--enable-libaom \
--enable-libass \
--enable-libdav1d \
--enable-libdrm \
--enable-libfreetype \
--enable-libfribidi \
--enable-libjack \
--enable-libmfx \
--enable-libopenjpeg \
--enable-libopenmpt \
--enable-libopus \
--enable-libpulse \
--enable-librist \
--enable-librsvg \
--enable-libspeex \
--enable-libsrt \
--enable-libssh \
--enable-libsvtav1 \
--enable-libtheora \
--enable-libv4l2 \
--enable-libvidstab \
--enable-libvorbis \
--enable-libvpx \
--enable-libwebp \
--enable-libx264 \
--enable-libx265 \
--enable-libxcb \
--enable-libxml2 \
--enable-libxvid \
--enable-libzimg \
--enable-shared \
--enable-vapoursynth \
--enable-version3 \
--enable-vulkan \
--disable-asm
make  %{?_smp_mflags}
popd
unset PKG_CONFIG_PATH
pushd ../buildavx512/
GOAMD64=v4
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -Wl,-z,x86-64-v4 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -Wl,-z,x86-64-v4 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -Wl,-z,x86-64-v4 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v4 -mprefer-vector-width=256 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -march=x86-64-v4 "
%configure --disable-static --disable-debug \
--disable-static \
--disable-stripping \
--enable-lto \
--enable-fontconfig \
--enable-gmp \
--enable-gnutls \
--enable-gpl \
--enable-ladspa \
--enable-libaom \
--enable-libass \
--enable-libdav1d \
--enable-libdrm \
--enable-libfreetype \
--enable-libfribidi \
--enable-libjack \
--enable-libmfx \
--enable-libopenjpeg \
--enable-libopenmpt \
--enable-libopus \
--enable-libpulse \
--enable-librist \
--enable-librsvg \
--enable-libspeex \
--enable-libsrt \
--enable-libssh \
--enable-libsvtav1 \
--enable-libtheora \
--enable-libv4l2 \
--enable-libvidstab \
--enable-libvorbis \
--enable-libvpx \
--enable-libwebp \
--enable-libx264 \
--enable-libx265 \
--enable-libxcb \
--enable-libxml2 \
--enable-libxvid \
--enable-libzimg \
--enable-shared \
--enable-vapoursynth \
--enable-version3 \
--enable-vulkan \
--disable-asm
make  %{?_smp_mflags}
popd
%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fno-semantic-interposition -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fno-semantic-interposition -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fno-semantic-interposition -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fno-semantic-interposition -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1731027632
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/compat-ffmpeg-6
cp %{_builddir}/ffmpeg-%{version}/COPYING.GPLv2 %{buildroot}/usr/share/package-licenses/compat-ffmpeg-6/4cc77b90af91e615a64ae04893fdffa7939db84c || :
cp %{_builddir}/ffmpeg-%{version}/COPYING.GPLv3 %{buildroot}/usr/share/package-licenses/compat-ffmpeg-6/8624bcdae55baeef00cd11d5dfcfa60f68710a02 || :
cp %{_builddir}/ffmpeg-%{version}/COPYING.LGPLv2.1 %{buildroot}/usr/share/package-licenses/compat-ffmpeg-6/37d2f1d62fec4da0caf06e5da21afc3521b597aa || :
cp %{_builddir}/ffmpeg-%{version}/COPYING.LGPLv3 %{buildroot}/usr/share/package-licenses/compat-ffmpeg-6/f45ee1c765646813b442ca58de72e20a64a7ddba || :
export GOAMD64=v2
GOAMD64=v3
pushd ../buildavx2/
%make_install_v3
popd
GOAMD64=v4
pushd ../buildavx512/
%make_install_v4
popd
GOAMD64=v2
%make_install
## Remove excluded files
rm -f %{buildroot}*/usr/bin/ffmpeg
rm -f %{buildroot}*/usr/bin/ffplay
rm -f %{buildroot}*/V3/usr/bin/ffprobe
rm -f %{buildroot}*/V4/usr/bin/ffprobe
rm -f %{buildroot}*/usr/bin/ffprobe
rm -f %{buildroot}*/usr/include/libavcodec/ac3_parser.h
rm -f %{buildroot}*/usr/include/libavcodec/adts_parser.h
rm -f %{buildroot}*/usr/include/libavcodec/avcodec.h
rm -f %{buildroot}*/usr/include/libavcodec/avdct.h
rm -f %{buildroot}*/usr/include/libavcodec/avfft.h
rm -f %{buildroot}*/usr/include/libavcodec/bsf.h
rm -f %{buildroot}*/usr/include/libavcodec/codec.h
rm -f %{buildroot}*/usr/include/libavcodec/codec_desc.h
rm -f %{buildroot}*/usr/include/libavcodec/codec_id.h
rm -f %{buildroot}*/usr/include/libavcodec/codec_par.h
rm -f %{buildroot}*/usr/include/libavcodec/d3d11va.h
rm -f %{buildroot}*/usr/include/libavcodec/defs.h
rm -f %{buildroot}*/usr/include/libavcodec/dirac.h
rm -f %{buildroot}*/usr/include/libavcodec/dv_profile.h
rm -f %{buildroot}*/usr/include/libavcodec/dxva2.h
rm -f %{buildroot}*/usr/include/libavcodec/jni.h
rm -f %{buildroot}*/usr/include/libavcodec/mediacodec.h
rm -f %{buildroot}*/usr/include/libavcodec/packet.h
rm -f %{buildroot}*/usr/include/libavcodec/qsv.h
rm -f %{buildroot}*/usr/include/libavcodec/vdpau.h
rm -f %{buildroot}*/usr/include/libavcodec/version.h
rm -f %{buildroot}*/usr/include/libavcodec/version_major.h
rm -f %{buildroot}*/usr/include/libavcodec/videotoolbox.h
rm -f %{buildroot}*/usr/include/libavcodec/vorbis_parser.h
rm -f %{buildroot}*/usr/include/libavcodec/xvmc.h
rm -f %{buildroot}*/usr/include/libavdevice/avdevice.h
rm -f %{buildroot}*/usr/include/libavdevice/version.h
rm -f %{buildroot}*/usr/include/libavdevice/version_major.h
rm -f %{buildroot}*/usr/include/libavfilter/avfilter.h
rm -f %{buildroot}*/usr/include/libavfilter/buffersink.h
rm -f %{buildroot}*/usr/include/libavfilter/buffersrc.h
rm -f %{buildroot}*/usr/include/libavfilter/version.h
rm -f %{buildroot}*/usr/include/libavfilter/version_major.h
rm -f %{buildroot}*/usr/include/libavformat/avformat.h
rm -f %{buildroot}*/usr/include/libavformat/avio.h
rm -f %{buildroot}*/usr/include/libavformat/version.h
rm -f %{buildroot}*/usr/include/libavformat/version_major.h
rm -f %{buildroot}*/usr/include/libavutil/adler32.h
rm -f %{buildroot}*/usr/include/libavutil/aes.h
rm -f %{buildroot}*/usr/include/libavutil/aes_ctr.h
rm -f %{buildroot}*/usr/include/libavutil/ambient_viewing_environment.h
rm -f %{buildroot}*/usr/include/libavutil/attributes.h
rm -f %{buildroot}*/usr/include/libavutil/audio_fifo.h
rm -f %{buildroot}*/usr/include/libavutil/avassert.h
rm -f %{buildroot}*/usr/include/libavutil/avconfig.h
rm -f %{buildroot}*/usr/include/libavutil/avstring.h
rm -f %{buildroot}*/usr/include/libavutil/avutil.h
rm -f %{buildroot}*/usr/include/libavutil/base64.h
rm -f %{buildroot}*/usr/include/libavutil/blowfish.h
rm -f %{buildroot}*/usr/include/libavutil/bprint.h
rm -f %{buildroot}*/usr/include/libavutil/bswap.h
rm -f %{buildroot}*/usr/include/libavutil/buffer.h
rm -f %{buildroot}*/usr/include/libavutil/camellia.h
rm -f %{buildroot}*/usr/include/libavutil/cast5.h
rm -f %{buildroot}*/usr/include/libavutil/channel_layout.h
rm -f %{buildroot}*/usr/include/libavutil/common.h
rm -f %{buildroot}*/usr/include/libavutil/cpu.h
rm -f %{buildroot}*/usr/include/libavutil/crc.h
rm -f %{buildroot}*/usr/include/libavutil/csp.h
rm -f %{buildroot}*/usr/include/libavutil/des.h
rm -f %{buildroot}*/usr/include/libavutil/detection_bbox.h
rm -f %{buildroot}*/usr/include/libavutil/dict.h
rm -f %{buildroot}*/usr/include/libavutil/display.h
rm -f %{buildroot}*/usr/include/libavutil/dovi_meta.h
rm -f %{buildroot}*/usr/include/libavutil/downmix_info.h
rm -f %{buildroot}*/usr/include/libavutil/encryption_info.h
rm -f %{buildroot}*/usr/include/libavutil/error.h
rm -f %{buildroot}*/usr/include/libavutil/eval.h
rm -f %{buildroot}*/usr/include/libavutil/ffversion.h
rm -f %{buildroot}*/usr/include/libavutil/fifo.h
rm -f %{buildroot}*/usr/include/libavutil/file.h
rm -f %{buildroot}*/usr/include/libavutil/film_grain_params.h
rm -f %{buildroot}*/usr/include/libavutil/frame.h
rm -f %{buildroot}*/usr/include/libavutil/hash.h
rm -f %{buildroot}*/usr/include/libavutil/hdr_dynamic_metadata.h
rm -f %{buildroot}*/usr/include/libavutil/hdr_dynamic_vivid_metadata.h
rm -f %{buildroot}*/usr/include/libavutil/hmac.h
rm -f %{buildroot}*/usr/include/libavutil/hwcontext.h
rm -f %{buildroot}*/usr/include/libavutil/hwcontext_cuda.h
rm -f %{buildroot}*/usr/include/libavutil/hwcontext_d3d11va.h
rm -f %{buildroot}*/usr/include/libavutil/hwcontext_drm.h
rm -f %{buildroot}*/usr/include/libavutil/hwcontext_dxva2.h
rm -f %{buildroot}*/usr/include/libavutil/hwcontext_mediacodec.h
rm -f %{buildroot}*/usr/include/libavutil/hwcontext_opencl.h
rm -f %{buildroot}*/usr/include/libavutil/hwcontext_qsv.h
rm -f %{buildroot}*/usr/include/libavutil/hwcontext_vaapi.h
rm -f %{buildroot}*/usr/include/libavutil/hwcontext_vdpau.h
rm -f %{buildroot}*/usr/include/libavutil/hwcontext_videotoolbox.h
rm -f %{buildroot}*/usr/include/libavutil/hwcontext_vulkan.h
rm -f %{buildroot}*/usr/include/libavutil/imgutils.h
rm -f %{buildroot}*/usr/include/libavutil/intfloat.h
rm -f %{buildroot}*/usr/include/libavutil/intreadwrite.h
rm -f %{buildroot}*/usr/include/libavutil/lfg.h
rm -f %{buildroot}*/usr/include/libavutil/log.h
rm -f %{buildroot}*/usr/include/libavutil/lzo.h
rm -f %{buildroot}*/usr/include/libavutil/macros.h
rm -f %{buildroot}*/usr/include/libavutil/mastering_display_metadata.h
rm -f %{buildroot}*/usr/include/libavutil/mathematics.h
rm -f %{buildroot}*/usr/include/libavutil/md5.h
rm -f %{buildroot}*/usr/include/libavutil/mem.h
rm -f %{buildroot}*/usr/include/libavutil/motion_vector.h
rm -f %{buildroot}*/usr/include/libavutil/murmur3.h
rm -f %{buildroot}*/usr/include/libavutil/opt.h
rm -f %{buildroot}*/usr/include/libavutil/parseutils.h
rm -f %{buildroot}*/usr/include/libavutil/pixdesc.h
rm -f %{buildroot}*/usr/include/libavutil/pixelutils.h
rm -f %{buildroot}*/usr/include/libavutil/pixfmt.h
rm -f %{buildroot}*/usr/include/libavutil/random_seed.h
rm -f %{buildroot}*/usr/include/libavutil/rational.h
rm -f %{buildroot}*/usr/include/libavutil/rc4.h
rm -f %{buildroot}*/usr/include/libavutil/replaygain.h
rm -f %{buildroot}*/usr/include/libavutil/ripemd.h
rm -f %{buildroot}*/usr/include/libavutil/samplefmt.h
rm -f %{buildroot}*/usr/include/libavutil/sha.h
rm -f %{buildroot}*/usr/include/libavutil/sha512.h
rm -f %{buildroot}*/usr/include/libavutil/spherical.h
rm -f %{buildroot}*/usr/include/libavutil/stereo3d.h
rm -f %{buildroot}*/usr/include/libavutil/tea.h
rm -f %{buildroot}*/usr/include/libavutil/threadmessage.h
rm -f %{buildroot}*/usr/include/libavutil/time.h
rm -f %{buildroot}*/usr/include/libavutil/timecode.h
rm -f %{buildroot}*/usr/include/libavutil/timestamp.h
rm -f %{buildroot}*/usr/include/libavutil/tree.h
rm -f %{buildroot}*/usr/include/libavutil/twofish.h
rm -f %{buildroot}*/usr/include/libavutil/tx.h
rm -f %{buildroot}*/usr/include/libavutil/uuid.h
rm -f %{buildroot}*/usr/include/libavutil/version.h
rm -f %{buildroot}*/usr/include/libavutil/video_enc_params.h
rm -f %{buildroot}*/usr/include/libavutil/xtea.h
rm -f %{buildroot}*/usr/include/libpostproc/postprocess.h
rm -f %{buildroot}*/usr/include/libpostproc/version.h
rm -f %{buildroot}*/usr/include/libpostproc/version_major.h
rm -f %{buildroot}*/usr/include/libswresample/swresample.h
rm -f %{buildroot}*/usr/include/libswresample/version.h
rm -f %{buildroot}*/usr/include/libswresample/version_major.h
rm -f %{buildroot}*/usr/include/libswscale/swscale.h
rm -f %{buildroot}*/usr/include/libswscale/version.h
rm -f %{buildroot}*/usr/include/libswscale/version_major.h
rm -f %{buildroot}*/usr/lib64/libavcodec.so
rm -f %{buildroot}*/usr/lib64/libavdevice.so
rm -f %{buildroot}*/usr/lib64/libavfilter.so
rm -f %{buildroot}*/usr/lib64/libavformat.so
rm -f %{buildroot}*/usr/lib64/libavutil.so
rm -f %{buildroot}*/usr/lib64/libpostproc.so
rm -f %{buildroot}*/usr/lib64/libswresample.so
rm -f %{buildroot}*/usr/lib64/libswscale.so
rm -f %{buildroot}*/usr/lib64/pkgconfig/libavcodec.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/libavdevice.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/libavfilter.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/libavformat.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/libavutil.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/libpostproc.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/libswresample.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/libswscale.pc
rm -f %{buildroot}*/usr/share/examples/Makefile
rm -f %{buildroot}*/usr/share/examples/README
rm -f %{buildroot}*/usr/share/examples/avio_http_serve_files.c
rm -f %{buildroot}*/usr/share/examples/avio_list_dir.c
rm -f %{buildroot}*/usr/share/examples/avio_read_callback.c
rm -f %{buildroot}*/usr/share/examples/decode_audio.c
rm -f %{buildroot}*/usr/share/examples/decode_filter_audio.c
rm -f %{buildroot}*/usr/share/examples/decode_filter_video.c
rm -f %{buildroot}*/usr/share/examples/decode_video.c
rm -f %{buildroot}*/usr/share/examples/demux_decode.c
rm -f %{buildroot}*/usr/share/examples/encode_audio.c
rm -f %{buildroot}*/usr/share/examples/encode_video.c
rm -f %{buildroot}*/usr/share/examples/extract_mvs.c
rm -f %{buildroot}*/usr/share/examples/filter_audio.c
rm -f %{buildroot}*/usr/share/examples/hw_decode.c
rm -f %{buildroot}*/usr/share/examples/mux.c
rm -f %{buildroot}*/usr/share/examples/qsv_decode.c
rm -f %{buildroot}*/usr/share/examples/qsv_transcode.c
rm -f %{buildroot}*/usr/share/examples/remux.c
rm -f %{buildroot}*/usr/share/examples/resample_audio.c
rm -f %{buildroot}*/usr/share/examples/scale_video.c
rm -f %{buildroot}*/usr/share/examples/show_metadata.c
rm -f %{buildroot}*/usr/share/examples/transcode.c
rm -f %{buildroot}*/usr/share/examples/transcode_aac.c
rm -f %{buildroot}*/usr/share/examples/vaapi_encode.c
rm -f %{buildroot}*/usr/share/examples/vaapi_transcode.c
rm -f %{buildroot}*/usr/share/ffprobe.xsd
rm -f %{buildroot}*/usr/share/libvpx-1080p.ffpreset
rm -f %{buildroot}*/usr/share/libvpx-1080p50_60.ffpreset
rm -f %{buildroot}*/usr/share/libvpx-360p.ffpreset
rm -f %{buildroot}*/usr/share/libvpx-720p.ffpreset
rm -f %{buildroot}*/usr/share/libvpx-720p50_60.ffpreset
rm -f %{buildroot}*/usr/share/man/man1/ffmpeg-all.1
rm -f %{buildroot}*/usr/share/man/man1/ffmpeg-bitstream-filters.1
rm -f %{buildroot}*/usr/share/man/man1/ffmpeg-codecs.1
rm -f %{buildroot}*/usr/share/man/man1/ffmpeg-devices.1
rm -f %{buildroot}*/usr/share/man/man1/ffmpeg-filters.1
rm -f %{buildroot}*/usr/share/man/man1/ffmpeg-formats.1
rm -f %{buildroot}*/usr/share/man/man1/ffmpeg-protocols.1
rm -f %{buildroot}*/usr/share/man/man1/ffmpeg-resampler.1
rm -f %{buildroot}*/usr/share/man/man1/ffmpeg-scaler.1
rm -f %{buildroot}*/usr/share/man/man1/ffmpeg-utils.1
rm -f %{buildroot}*/usr/share/man/man1/ffmpeg.1
rm -f %{buildroot}*/usr/share/man/man1/ffplay-all.1
rm -f %{buildroot}*/usr/share/man/man1/ffplay.1
rm -f %{buildroot}*/usr/share/man/man1/ffprobe-all.1
rm -f %{buildroot}*/usr/share/man/man1/ffprobe.1
rm -f %{buildroot}*/usr/share/man/man3/libavcodec.3
rm -f %{buildroot}*/usr/share/man/man3/libavdevice.3
rm -f %{buildroot}*/usr/share/man/man3/libavfilter.3
rm -f %{buildroot}*/usr/share/man/man3/libavformat.3
rm -f %{buildroot}*/usr/share/man/man3/libavutil.3
rm -f %{buildroot}*/usr/share/man/man3/libswresample.3
rm -f %{buildroot}*/usr/share/man/man3/libswscale.3
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libavcodec.so.60.3.100
/V3/usr/lib64/libavdevice.so.60.1.100
/V3/usr/lib64/libavfilter.so.9.3.100
/V3/usr/lib64/libavformat.so.60.3.100
/V3/usr/lib64/libavutil.so.58.2.100
/V3/usr/lib64/libpostproc.so.57.1.100
/V3/usr/lib64/libswresample.so.4.10.100
/V3/usr/lib64/libswscale.so.7.1.100
/V4/usr/lib64/libavcodec.so.60.3.100
/V4/usr/lib64/libavdevice.so.60.1.100
/V4/usr/lib64/libavfilter.so.9.3.100
/V4/usr/lib64/libavformat.so.60.3.100
/V4/usr/lib64/libavutil.so.58.2.100
/V4/usr/lib64/libpostproc.so.57.1.100
/V4/usr/lib64/libswresample.so.4.10.100
/V4/usr/lib64/libswscale.so.7.1.100
/usr/lib64/libavcodec.so.60
/usr/lib64/libavcodec.so.60.3.100
/usr/lib64/libavdevice.so.60
/usr/lib64/libavdevice.so.60.1.100
/usr/lib64/libavfilter.so.9
/usr/lib64/libavfilter.so.9.3.100
/usr/lib64/libavformat.so.60
/usr/lib64/libavformat.so.60.3.100
/usr/lib64/libavutil.so.58
/usr/lib64/libavutil.so.58.2.100
/usr/lib64/libpostproc.so.57
/usr/lib64/libpostproc.so.57.1.100
/usr/lib64/libswresample.so.4
/usr/lib64/libswresample.so.4.10.100
/usr/lib64/libswscale.so.7
/usr/lib64/libswscale.so.7.1.100

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/compat-ffmpeg-6/37d2f1d62fec4da0caf06e5da21afc3521b597aa
/usr/share/package-licenses/compat-ffmpeg-6/4cc77b90af91e615a64ae04893fdffa7939db84c
/usr/share/package-licenses/compat-ffmpeg-6/8624bcdae55baeef00cd11d5dfcfa60f68710a02
/usr/share/package-licenses/compat-ffmpeg-6/f45ee1c765646813b442ca58de72e20a64a7ddba
